//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YewCone.AudiobookGenerator.Console.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YewCone.AudiobookGenerator.Console.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string ColumnAge {
            get {
                return ResourceManager.GetString("ColumnAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        internal static string ColumnCommand {
            get {
                return ResourceManager.GetString("ColumnCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover.
        /// </summary>
        internal static string ColumnCover {
            get {
                return ResourceManager.GetString("ColumnCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        internal static string ColumnCulture {
            get {
                return ResourceManager.GetString("ColumnCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ColumnDescription {
            get {
                return ResourceManager.GetString("ColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        internal static string ColumnExample {
            get {
                return ResourceManager.GetString("ColumnExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        internal static string ColumnField {
            get {
                return ResourceManager.GetString("ColumnField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        internal static string ColumnFilename {
            get {
                return ResourceManager.GetString("ColumnFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string ColumnGender {
            get {
                return ResourceManager.GetString("ColumnGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        internal static string ColumnNumber {
            get {
                return ResourceManager.GetString("ColumnNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string ColumnSetting {
            get {
                return ResourceManager.GetString("ColumnSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string ColumnSize {
            get {
                return ResourceManager.GetString("ColumnSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string ColumnValue {
            get {
                return ResourceManager.GetString("ColumnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... (content truncated for display).
        /// </summary>
        internal static string ContentTruncated {
            get {
                return ResourceManager.GetString("ContentTruncated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one author is required..
        /// </summary>
        internal static string ErrorAtLeastOneAuthor {
            get {
                return ResourceManager.GetString("ErrorAtLeastOneAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove the last author..
        /// </summary>
        internal static string ErrorCannotRemoveLastAuthor {
            get {
                return ResourceManager.GetString("ErrorCannotRemoveLastAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion failed: {0}.
        /// </summary>
        internal static string ErrorConversionFailed {
            get {
                return ResourceManager.GetString("ErrorConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to convert command requires a file path.
        /// </summary>
        internal static string ErrorConvertRequiresFile {
            get {
                return ResourceManager.GetString("ErrorConvertRequiresFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory does not exist..
        /// </summary>
        internal static string ErrorDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist..
        /// </summary>
        internal static string ErrorFileDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File must be an EPUB..
        /// </summary>
        internal static string ErrorFileMustBeEpub {
            get {
                return ResourceManager.GetString("ErrorFileMustBeEpub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found: {0}.
        /// </summary>
        internal static string ErrorFileNotFound {
            get {
                return ResourceManager.GetString("ErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info command requires a file path.
        /// </summary>
        internal static string ErrorInfoRequiresFile {
            get {
                return ResourceManager.GetString("ErrorInfoRequiresFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty..
        /// </summary>
        internal static string ErrorNameEmpty {
            get {
                return ResourceManager.GetString("ErrorNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No images available. Add an image first..
        /// </summary>
        internal static string ErrorNoImagesAvailable {
            get {
                return ResourceManager.GetString("ErrorNoImagesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No images to save..
        /// </summary>
        internal static string ErrorNoImagesToSave {
            get {
                return ResourceManager.GetString("ErrorNoImagesToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No voice selected. Please select a voice first..
        /// </summary>
        internal static string ErrorNoVoiceSelected {
            get {
                return ResourceManager.GetString("ErrorNoVoiceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No voice selected..
        /// </summary>
        internal static string ErrorNoVoiceSelectedShort {
            get {
                return ResourceManager.GetString("ErrorNoVoiceSelectedShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No TTS voices found on this system..
        /// </summary>
        internal static string ErrorNoVoicesFound {
            get {
                return ResourceManager.GetString("ErrorNoVoicesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output directory not found: {0}.
        /// </summary>
        internal static string ErrorOutputDirNotFound {
            get {
                return ResourceManager.GetString("ErrorOutputDirNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path cannot be empty..
        /// </summary>
        internal static string ErrorPathEmpty {
            get {
                return ResourceManager.GetString("ErrorPathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error playing audio: {0}.
        /// </summary>
        internal static string ErrorPlayingAudio {
            get {
                return ResourceManager.GetString("ErrorPlayingAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a voice first..
        /// </summary>
        internal static string ErrorSelectVoiceFirst {
            get {
                return ResourceManager.GetString("ErrorSelectVoiceFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text cannot be empty..
        /// </summary>
        internal static string ErrorTextEmpty {
            get {
                return ResourceManager.GetString("ErrorTextEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text not found in chapter..
        /// </summary>
        internal static string ErrorTextNotFound {
            get {
                return ResourceManager.GetString("ErrorTextNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title cannot be empty..
        /// </summary>
        internal static string ErrorTitleEmpty {
            get {
                return ResourceManager.GetString("ErrorTitleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command: {0}.
        /// </summary>
        internal static string ErrorUnknownCommand {
            get {
                return ResourceManager.GetString("ErrorUnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported image format. Use JPG, PNG, GIF, or WebP..
        /// </summary>
        internal static string ErrorUnsupportedImageFormat {
            get {
                return ResourceManager.GetString("ErrorUnsupportedImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice not found: {0}.
        /// </summary>
        internal static string ErrorVoiceNotFound {
            get {
                return ResourceManager.GetString("ErrorVoiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audiobook Generator.
        /// </summary>
        internal static string HeaderAudiobookGenerator {
            get {
                return ResourceManager.GetString("HeaderAudiobookGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available TTS Voices.
        /// </summary>
        internal static string HeaderAvailableTTSVoices {
            get {
                return ResourceManager.GetString("HeaderAvailableTTSVoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audiobook Generator - Direct Conversion.
        /// </summary>
        internal static string HeaderDirectConversion {
            get {
                return ResourceManager.GetString("HeaderDirectConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Chapters.
        /// </summary>
        internal static string HeaderEditChapters {
            get {
                return ResourceManager.GetString("HeaderEditChapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Metadata.
        /// </summary>
        internal static string HeaderEditMetadata {
            get {
                return ResourceManager.GetString("HeaderEditMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Full Content.
        /// </summary>
        internal static string HeaderFullContent {
            get {
                return ResourceManager.GetString("HeaderFullContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Audiobook.
        /// </summary>
        internal static string HeaderGenerateAudiobook {
            get {
                return ResourceManager.GetString("HeaderGenerateAudiobook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Images.
        /// </summary>
        internal static string HeaderManageImages {
            get {
                return ResourceManager.GetString("HeaderManageImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Audio.
        /// </summary>
        internal static string HeaderPreviewAudio {
            get {
                return ResourceManager.GetString("HeaderPreviewAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Voice.
        /// </summary>
        internal static string HeaderSelectVoice {
            get {
                return ResourceManager.GetString("HeaderSelectVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert EPUB directly to M4B.
        /// </summary>
        internal static string HelpConvertDescription {
            get {
                return ResourceManager.GetString("HelpConvertDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert options:.
        /// </summary>
        internal static string HelpConvertOptions {
            get {
                return ResourceManager.GetString("HelpConvertOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show this help message.
        /// </summary>
        internal static string HelpHelpDescription {
            get {
                return ResourceManager.GetString("HelpHelpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display book information.
        /// </summary>
        internal static string HelpInfoDescription {
            get {
                return ResourceManager.GetString("HelpInfoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open EPUB in interactive editor.
        /// </summary>
        internal static string HelpOpenDescription {
            get {
                return ResourceManager.GetString("HelpOpenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --output &lt;dir&gt;    Output directory (default: book&apos;s directory).
        /// </summary>
        internal static string HelpOutputOption {
            get {
                return ResourceManager.GetString("HelpOutputOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: You can also drag and drop an EPUB file onto the executable..
        /// </summary>
        internal static string HelpTipDragDrop {
            get {
                return ResourceManager.GetString("HelpTipDragDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --voice &lt;name&gt;    TTS voice name (partial match).
        /// </summary>
        internal static string HelpVoiceOption {
            get {
                return ResourceManager.GetString("HelpVoiceOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List available TTS voices.
        /// </summary>
        internal static string HelpVoicesDescription {
            get {
                return ResourceManager.GetString("HelpVoicesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing chapter content. The current content will be shown..
        /// </summary>
        internal static string HintEditingChapter1 {
            get {
                return ResourceManager.GetString("HintEditingChapter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can modify it and press Enter when done..
        /// </summary>
        internal static string HintEditingChapter2 {
            get {
                return ResourceManager.GetString("HintEditingChapter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: For long content, consider using an external editor..
        /// </summary>
        internal static string HintEditingChapter3 {
            get {
                return ResourceManager.GetString("HintEditingChapter3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install additional voices via Windows Settings &gt; Time &amp; Language &gt; Speech..
        /// </summary>
        internal static string HintInstallVoices {
            get {
                return ResourceManager.GetString("HintInstallVoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        internal static string LabelAuthors {
            get {
                return ResourceManager.GetString("LabelAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        internal static string LabelBook {
            get {
                return ResourceManager.GetString("LabelBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapters.
        /// </summary>
        internal static string LabelChapters {
            get {
                return ResourceManager.GetString("LabelChapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} characters.
        /// </summary>
        internal static string LabelCharactersCount {
            get {
                return ResourceManager.GetString("LabelCharactersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string LabelContent {
            get {
                return ResourceManager.GetString("LabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Cover).
        /// </summary>
        internal static string LabelCover {
            get {
                return ResourceManager.GetString("LabelCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string LabelDescription {
            get {
                return ResourceManager.GetString("LabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Cover.
        /// </summary>
        internal static string LabelHasCover {
            get {
                return ResourceManager.GetString("LabelHasCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        internal static string LabelImages {
            get {
                return ResourceManager.GetString("LabelImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string LabelNo {
            get {
                return ResourceManager.GetString("LabelNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string LabelOutput {
            get {
                return ResourceManager.GetString("LabelOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string LabelTitle {
            get {
                return ResourceManager.GetString("LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice.
        /// </summary>
        internal static string LabelVoice {
            get {
                return ResourceManager.GetString("LabelVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string LabelYes {
            get {
                return ResourceManager.GetString("LabelYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Add author.
        /// </summary>
        internal static string MenuAddAuthor {
            get {
                return ResourceManager.GetString("MenuAddAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Add Image from File.
        /// </summary>
        internal static string MenuAddImageFromFile {
            get {
                return ResourceManager.GetString("MenuAddImageFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ← Back to Chapter List.
        /// </summary>
        internal static string MenuBackToChapterList {
            get {
                return ResourceManager.GetString("MenuBackToChapterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ← Back to Main Menu.
        /// </summary>
        internal static string MenuBackToMainMenu {
            get {
                return ResourceManager.GetString("MenuBackToMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ← Cancel.
        /// </summary>
        internal static string MenuCancel {
            get {
                return ResourceManager.GetString("MenuCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Clear Cover Image.
        /// </summary>
        internal static string MenuClearCoverImage {
            get {
                return ResourceManager.GetString("MenuClearCoverImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👤 Edit Authors.
        /// </summary>
        internal static string MenuEditAuthors {
            get {
                return ResourceManager.GetString("MenuEditAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📖 Edit Chapters.
        /// </summary>
        internal static string MenuEditChapters {
            get {
                return ResourceManager.GetString("MenuEditChapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✏️  Edit Content.
        /// </summary>
        internal static string MenuEditContent {
            get {
                return ResourceManager.GetString("MenuEditContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📝 Edit Description.
        /// </summary>
        internal static string MenuEditDescription {
            get {
                return ResourceManager.GetString("MenuEditDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📝 Edit in console (for small changes).
        /// </summary>
        internal static string MenuEditInConsole {
            get {
                return ResourceManager.GetString("MenuEditInConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📝 Edit Metadata.
        /// </summary>
        internal static string MenuEditMetadata {
            get {
                return ResourceManager.GetString("MenuEditMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📕 Edit Title.
        /// </summary>
        internal static string MenuEditTitle {
            get {
                return ResourceManager.GetString("MenuEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📝 Enter new description (single line).
        /// </summary>
        internal static string MenuEnterDescriptionSingleLine {
            get {
                return ResourceManager.GetString("MenuEnterDescriptionSingleLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📖 Entire chapter (may take a while).
        /// </summary>
        internal static string MenuEntireChapter {
            get {
                return ResourceManager.GetString("MenuEntireChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚪 Exit.
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✂️  Find and replace text.
        /// </summary>
        internal static string MenuFindAndReplace {
            get {
                return ResourceManager.GetString("MenuFindAndReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📄 First 2000 characters.
        /// </summary>
        internal static string MenuFirst2000Chars {
            get {
                return ResourceManager.GetString("MenuFirst2000Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📝 First 500 characters.
        /// </summary>
        internal static string MenuFirst500Chars {
            get {
                return ResourceManager.GetString("MenuFirst500Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎧 Generate Audiobook.
        /// </summary>
        internal static string MenuGenerateAudiobook {
            get {
                return ResourceManager.GetString("MenuGenerateAudiobook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🖼️  Manage Images.
        /// </summary>
        internal static string MenuManageImages {
            get {
                return ResourceManager.GetString("MenuManageImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔊 Preview Audio.
        /// </summary>
        internal static string MenuPreviewAudio {
            get {
                return ResourceManager.GetString("MenuPreviewAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔊 Preview custom text.
        /// </summary>
        internal static string MenuPreviewCustomText {
            get {
                return ResourceManager.GetString("MenuPreviewCustomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➖ Remove author.
        /// </summary>
        internal static string MenuRemoveAuthor {
            get {
                return ResourceManager.GetString("MenuRemoveAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔄 Replace all authors.
        /// </summary>
        internal static string MenuReplaceAllAuthors {
            get {
                return ResourceManager.GetString("MenuReplaceAllAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔄 Replace entire content.
        /// </summary>
        internal static string MenuReplaceEntireContent {
            get {
                return ResourceManager.GetString("MenuReplaceEntireContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔄 Replace with multiline input.
        /// </summary>
        internal static string MenuReplaceMultiline {
            get {
                return ResourceManager.GetString("MenuReplaceMultiline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💾 Save Image to Disk.
        /// </summary>
        internal static string MenuSaveImageToDisk {
            get {
                return ResourceManager.GetString("MenuSaveImageToDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎤 Select Voice.
        /// </summary>
        internal static string MenuSelectVoice {
            get {
                return ResourceManager.GetString("MenuSelectVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🖼️  Set Cover Image.
        /// </summary>
        internal static string MenuSetCoverImage {
            get {
                return ResourceManager.GetString("MenuSetCoverImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ℹ️  Show Book Info.
        /// </summary>
        internal static string MenuShowBookInfo {
            get {
                return ResourceManager.GetString("MenuShowBookInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏹️  Stop playback.
        /// </summary>
        internal static string MenuStopPlayback {
            get {
                return ResourceManager.GetString("MenuStopPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📋 View Full Content.
        /// </summary>
        internal static string MenuViewFullContent {
            get {
                return ResourceManager.GetString("MenuViewFullContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes. Are you sure you want to exit?.
        /// </summary>
        internal static string PromptConfirmExitUnsaved {
            get {
                return ResourceManager.GetString("PromptConfirmExitUnsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; already exists. Overwrite?.
        /// </summary>
        internal static string PromptConfirmOverwrite {
            get {
                return ResourceManager.GetString("PromptConfirmOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter author name:.
        /// </summary>
        internal static string PromptEnterAuthorName {
            get {
                return ResourceManager.GetString("PromptEnterAuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter authors (comma-separated):.
        /// </summary>
        internal static string PromptEnterAuthors {
            get {
                return ResourceManager.GetString("PromptEnterAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new description (end with an empty line):.
        /// </summary>
        internal static string PromptEnterDescriptionEndEmpty {
            get {
                return ResourceManager.GetString("PromptEnterDescriptionEndEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter path to EPUB file:.
        /// </summary>
        internal static string PromptEnterEpubPath {
            get {
                return ResourceManager.GetString("PromptEnterEpubPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter path to image file:.
        /// </summary>
        internal static string PromptEnterImagePath {
            get {
                return ResourceManager.GetString("PromptEnterImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new content:.
        /// </summary>
        internal static string PromptEnterNewContent {
            get {
                return ResourceManager.GetString("PromptEnterNewContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new description:.
        /// </summary>
        internal static string PromptEnterNewDescription {
            get {
                return ResourceManager.GetString("PromptEnterNewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new title:.
        /// </summary>
        internal static string PromptEnterNewTitle {
            get {
                return ResourceManager.GetString("PromptEnterNewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text to preview:.
        /// </summary>
        internal static string PromptEnterTextToPreview {
            get {
                return ResourceManager.GetString("PromptEnterTextToPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much to preview?.
        /// </summary>
        internal static string PromptHowMuchToPreview {
            get {
                return ResourceManager.GetString("PromptHowMuchToPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How would you like to edit?.
        /// </summary>
        internal static string PromptHowToEdit {
            get {
                return ResourceManager.GetString("PromptHowToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output directory:.
        /// </summary>
        internal static string PromptOutputDirectory {
            get {
                return ResourceManager.GetString("PromptOutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste your new content (end with an empty line):.
        /// </summary>
        internal static string PromptPasteNewContent {
            get {
                return ResourceManager.GetString("PromptPasteNewContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with:.
        /// </summary>
        internal static string PromptReplaceWith {
            get {
                return ResourceManager.GetString("PromptReplaceWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to directory:.
        /// </summary>
        internal static string PromptSaveToDirectory {
            get {
                return ResourceManager.GetString("PromptSaveToDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select author to remove:.
        /// </summary>
        internal static string PromptSelectAuthorToRemove {
            get {
                return ResourceManager.GetString("PromptSelectAuthorToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a chapter to view/edit:.
        /// </summary>
        internal static string PromptSelectChapter {
            get {
                return ResourceManager.GetString("PromptSelectChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a chapter to preview:.
        /// </summary>
        internal static string PromptSelectChapterToPreview {
            get {
                return ResourceManager.GetString("PromptSelectChapterToPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select image to set as cover:.
        /// </summary>
        internal static string PromptSelectImageAsCover {
            get {
                return ResourceManager.GetString("PromptSelectImageAsCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select image to save:.
        /// </summary>
        internal static string PromptSelectImageToSave {
            get {
                return ResourceManager.GetString("PromptSelectImageToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a voice for conversion:.
        /// </summary>
        internal static string PromptSelectVoice {
            get {
                return ResourceManager.GetString("PromptSelectVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set this image as the cover?.
        /// </summary>
        internal static string PromptSetAsCover {
            get {
                return ResourceManager.GetString("PromptSetAsCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start conversion?.
        /// </summary>
        internal static string PromptStartConversion {
            get {
                return ResourceManager.GetString("PromptStartConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to find:.
        /// </summary>
        internal static string PromptTextToFind {
            get {
                return ResourceManager.GetString("PromptTextToFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to do?.
        /// </summary>
        internal static string PromptWhatToDo {
            get {
                return ResourceManager.GetString("PromptWhatToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to edit?.
        /// </summary>
        internal static string PromptWhatToEdit {
            get {
                return ResourceManager.GetString("PromptWhatToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding metadata and cover.
        /// </summary>
        internal static string StageAddingMetadata {
            get {
                return ResourceManager.GetString("StageAddingMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting text to audio:.
        /// </summary>
        internal static string StageConvertTextToAudio {
            get {
                return ResourceManager.GetString("StageConvertTextToAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating audiobook file.
        /// </summary>
        internal static string StageCreatingAudiobook {
            get {
                return ResourceManager.GetString("StageCreatingAudiobook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding audio:.
        /// </summary>
        internal static string StageEncodingAudio {
            get {
                return ResourceManager.GetString("StageEncodingAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Failed).
        /// </summary>
        internal static string StageFailed {
            get {
                return ResourceManager.GetString("StageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing dependencies.
        /// </summary>
        internal static string StageInstallingDependencies {
            get {
                return ResourceManager.GetString("StageInstallingDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving image:.
        /// </summary>
        internal static string StageSavingImage {
            get {
                return ResourceManager.GetString("StageSavingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓ Audiobook saved to:.
        /// </summary>
        internal static string StatusAudiobookSaved {
            get {
                return ResourceManager.GetString("StatusAudiobookSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓ Author &apos;{0}&apos; added..
        /// </summary>
        internal static string StatusAuthorAdded {
            get {
                return ResourceManager.GetString("StatusAuthorAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓ Author &apos;{0}&apos; removed..
        /// </summary>
        internal static string StatusAuthorRemoved {
            get {
                return ResourceManager.GetString("StatusAuthorRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓ Authors updated: {0}.
        /// </summary>
        internal static string StatusAuthorsUpdated {
            get {
                return ResourceManager.GetString("StatusAuthorsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available voices:.
        /// </summary>
        internal static string StatusAvailableVoices {
            get {
                return ResourceManager.GetString("StatusAvailableVoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓ Chapter content replaced..
        /// </summary>
        internal static string StatusChapterContentReplaced {
            get {
                return ResourceManager.GetString("StatusChapterContentReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓ Chapter content updated..
        /// </summary>
        internal static string StatusChapterContentUpdated {
            get {
                return ResourceManager.GetString("StatusChapterContentUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion cancelled..
        /// </summary>
        internal static string StatusConversionCancelled {
            get {
                return ResourceManager.GetString("StatusConversionCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Complete!.
        /// </summary>
        internal static string StatusConversionComplete {
            get {
                return ResourceManager.GetString("StatusConversionComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓ Cover image cleared..
        /// </summary>
        internal static string StatusCoverImageCleared {
            get {
                return ResourceManager.GetString("StatusCoverImageCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current authors: {0}.
        /// </summary>
        internal static string StatusCurrentAuthors {
            get {
                return ResourceManager.GetString("StatusCurrentAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current description:.
        /// </summary>
        internal static string StatusCurrentDescription {
            get {
                return ResourceManager.GetString("StatusCurrentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently selected: {0}.
        /// </summary>
        internal static string StatusCurrentlySelected {
            get {
                return ResourceManager.GetString("StatusCurrentlySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓ Description updated..
        /// </summary>
        internal static string StatusDescriptionUpdated {
            get {
                return ResourceManager.GetString("StatusDescriptionUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- End of content ---.
        /// </summary>
        internal static string StatusEndOfContent {
            get {
                return ResourceManager.GetString("StatusEndOfContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} occurrence(s)..
        /// </summary>
        internal static string StatusFoundOccurrences {
            get {
                return ResourceManager.GetString("StatusFoundOccurrences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodbye!.
        /// </summary>
        internal static string StatusGoodbye {
            get {
                return ResourceManager.GetString("StatusGoodbye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓ Image &apos;{0}&apos; added ({1} KB)..
        /// </summary>
        internal static string StatusImageAdded {
            get {
                return ResourceManager.GetString("StatusImageAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓ Image saved to &apos;{0}&apos;..
        /// </summary>
        internal static string StatusImageSaved {
            get {
                return ResourceManager.GetString("StatusImageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓ &apos;{0}&apos; set as cover image..
        /// </summary>
        internal static string StatusImageSetAsCover {
            get {
                return ResourceManager.GetString("StatusImageSetAsCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓ Image set as cover..
        /// </summary>
        internal static string StatusImageSetAsCoverShort {
            get {
                return ResourceManager.GetString("StatusImageSetAsCoverShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading book....
        /// </summary>
        internal static string StatusLoadingBook {
            get {
                return ResourceManager.GetString("StatusLoadingBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (modified).
        /// </summary>
        internal static string StatusModified {
            get {
                return ResourceManager.GetString("StatusModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No images in book..
        /// </summary>
        internal static string StatusNoImagesInBook {
            get {
                return ResourceManager.GetString("StatusNoImagesInBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Page {0}/{1} (Press Enter to continue, &apos;q&apos; to quit) ---.
        /// </summary>
        internal static string StatusPageProgress {
            get {
                return ResourceManager.GetString("StatusPageProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback stopped..
        /// </summary>
        internal static string StatusPlaybackStopped {
            get {
                return ResourceManager.GetString("StatusPlaybackStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing audio... (select &apos;Stop playback&apos; to stop).
        /// </summary>
        internal static string StatusPlayingAudio {
            get {
                return ResourceManager.GetString("StatusPlayingAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previewing: {0}.
        /// </summary>
        internal static string StatusPreviewing {
            get {
                return ResourceManager.GetString("StatusPreviewing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓ Replaced {0} occurrence(s)..
        /// </summary>
        internal static string StatusReplacedOccurrences {
            get {
                return ResourceManager.GetString("StatusReplacedOccurrences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting conversion... This may take a while depending on book length..
        /// </summary>
        internal static string StatusStartingConversion {
            get {
                return ResourceManager.GetString("StatusStartingConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓ Title updated to &apos;{0}&apos;..
        /// </summary>
        internal static string StatusTitleUpdated {
            get {
                return ResourceManager.GetString("StatusTitleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0} voice(s).
        /// </summary>
        internal static string StatusTotalVoices {
            get {
                return ResourceManager.GetString("StatusTotalVoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using voice: {0}.
        /// </summary>
        internal static string StatusUsingVoice {
            get {
                return ResourceManager.GetString("StatusUsingVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not selected.
        /// </summary>
        internal static string StatusVoiceNotSelected {
            get {
                return ResourceManager.GetString("StatusVoiceNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓ Voice set to &apos;{0}&apos;..
        /// </summary>
        internal static string StatusVoiceSet {
            get {
                return ResourceManager.GetString("StatusVoiceSet", resourceCulture);
            }
        }
    }
}
