<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Label="TargetFrameworks">
    <PortableAot>false</PortableAot>
    <WindowsTargetFramework>net10.0-windows</WindowsTargetFramework>
    <PortableTargetFramework>net10.0</PortableTargetFramework>
    <CurrentTargetFramework>$(WindowsTargetFramework)</CurrentTargetFramework>
    <CoreTargetFramework Condition="'$(PortableAot)' == 'true'">$(PortableTargetFramework)</CoreTargetFramework>
    <CoreTargetFramework Condition="'$(CoreTargetFramework)' == ''">$(WindowsTargetFramework)</CoreTargetFramework>
    <ConsoleTargetFramework Condition="'$(PortableAot)' == 'true'">$(PortableTargetFramework)</ConsoleTargetFramework>
    <ConsoleTargetFramework Condition="'$(ConsoleTargetFramework)' == ''">$(WindowsTargetFramework)</ConsoleTargetFramework>
    <WpfTargetFramework>$(WindowsTargetFramework)</WpfTargetFramework>
    <TestTargetFramework Condition="'$(PortableAot)' == 'true'">$(PortableTargetFramework)</TestTargetFramework>
    <TestTargetFramework Condition="'$(TestTargetFramework)' == ''">$(WindowsTargetFramework)</TestTargetFramework>
  </PropertyGroup>
  <PropertyGroup Label="PortableAot" Condition="'$(PortableAot)' == 'true'">
    <PortableAotSupportedRuntimeIdentifiers>win-x64;win-arm64;linux-x64;linux-arm64;osx-x64;osx-arm64</PortableAotSupportedRuntimeIdentifiers>
  </PropertyGroup>
  <PropertyGroup>
    <UseArtifactsOutput>true</UseArtifactsOutput>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPublishable>false</IsPublishable>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <PropertyGroup>
    <MajorVersion>0</MajorVersion>
    <VersionSufix Condition="$(GITHUB_REF) != '' AND $(GITHUB_REF) != 'refs/heads/main'">-$(GITHUB_SHA)</VersionSufix>
    <Version>$(MajorVersion).$([System.DateTime]::UtcNow.ToString("yyMM.ddHH.mmss"))$(VersionSufix)</Version>
  </PropertyGroup>
  <PropertyGroup Label="Signing">
    <SignAssembly>false</SignAssembly> <!-- disabled until VersOne.Epub is signed -->
    <DelaySign>false</DelaySign>
    <AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)\YewConeOssKey.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
</Project>