<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(TestTargetFramework)</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <PropertyGroup Label="PlatformSymbols">
    <DefineConstants Condition="'$(TargetFramework)' == '$(PortableTargetFramework)'">$(DefineConstants);AUDIOBOOKGENERATOR_PORTABLE</DefineConstants>
    <DefineConstants Condition="'$(TargetFramework)' != '$(PortableTargetFramework)'">$(DefineConstants);AUDIOBOOKGENERATOR_WINDOWS_CORE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\AudiobookGenerator.Core\YewCone.AudiobookGenerator.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
