//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YewCone.AudiobookGenerator.Wpf; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class Resources {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YewCone.AudiobookGenerator.Wpf.Resources", typeof(Resources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Add Image....
    /// </summary>
    public static string AddImageLable {
        get {
            return ResourceManager.GetString("AddImageLable", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Need more voices?.
    /// </summary>
    public static string AddVoiceLable {
        get {
            return ResourceManager.GetString("AddVoiceLable", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to https://support.microsoft.com/en-us/topic/download-languages-and-voices-for-immersive-reader-read-mode-and-read-aloud-4c83a8d8-7486-42f7-8e46-2b0fdf753130.
    /// </summary>
    public static string AddVoiceLink {
        get {
            return ResourceManager.GetString("AddVoiceLink", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Audiobook Generator.
    /// </summary>
    public static string AppName {
        get {
            return ResourceManager.GetString("AppName", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Authors.
    /// </summary>
    public static string AuthorsProperties {
        get {
            return ResourceManager.GetString("AuthorsProperties", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Error when opening book.
    /// </summary>
    public static string BookOpenError {
        get {
            return ResourceManager.GetString("BookOpenError", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Please select ebook file.
    /// </summary>
    public static string BookPathPlaceholder {
        get {
            return ResourceManager.GetString("BookPathPlaceholder", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Change Book....
    /// </summary>
    public static string ChangeBookLable {
        get {
            return ResourceManager.GetString("ChangeBookLable", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to ({0} chapters).
    /// </summary>
    public static string ChaptersLable {
        get {
            return ResourceManager.GetString("ChaptersLable", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Converting text to wav for.
    /// </summary>
    public static string ConvertTextToWavMessage {
        get {
            return ResourceManager.GetString("ConvertTextToWavMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Converting wav to aac for.
    /// </summary>
    public static string ConvertWavToAacMessage {
        get {
            return ResourceManager.GetString("ConvertWavToAacMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Cover Image.
    /// </summary>
    public static string CoverImageLable {
        get {
            return ResourceManager.GetString("CoverImageLable", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Description.
    /// </summary>
    public static string DescriptionProperty {
        get {
            return ResourceManager.GetString("DescriptionProperty", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Details.
    /// </summary>
    public static string DetailsSectionHeader {
        get {
            return ResourceManager.GetString("DetailsSectionHeader", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to finishing.
    /// </summary>
    public static string DoneMessage {
        get {
            return ResourceManager.GetString("DoneMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to failed.
    /// </summary>
    public static string FailedMessage {
        get {
            return ResourceManager.GetString("FailedMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Generate Audiobook.
    /// </summary>
    public static string GenerateLable {
        get {
            return ResourceManager.GetString("GenerateLable", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to ({0} images).
    /// </summary>
    public static string ImagesLable {
        get {
            return ResourceManager.GetString("ImagesLable", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Images.
    /// </summary>
    public static string ImagesSectionHeader {
        get {
            return ResourceManager.GetString("ImagesSectionHeader", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Installing component.
    /// </summary>
    public static string InstallingMessage {
        get {
            return ResourceManager.GetString("InstallingMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Merging files into m4b.
    /// </summary>
    public static string MergingIntoM4bMessage {
        get {
            return ResourceManager.GetString("MergingIntoM4bMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Please select ebook file.
    /// </summary>
    public static string NoBookPathPlaceholder {
        get {
            return ResourceManager.GetString("NoBookPathPlaceholder", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Play.
    /// </summary>
    public static string PlayTooltip {
        get {
            return ResourceManager.GetString("PlayTooltip", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Save Image As....
    /// </summary>
    public static string SaveImageAsLable {
        get {
            return ResourceManager.GetString("SaveImageAsLable", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Saving image.
    /// </summary>
    public static string SavingImageMessage {
        get {
            return ResourceManager.GetString("SavingImageMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Select Voice.
    /// </summary>
    public static string SelectVoiceLable {
        get {
            return ResourceManager.GetString("SelectVoiceLable", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to started.
    /// </summary>
    public static string StartedMessage {
        get {
            return ResourceManager.GetString("StartedMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Stop.
    /// </summary>
    public static string StopToolTip {
        get {
            return ResourceManager.GetString("StopToolTip", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Text Content.
    /// </summary>
    public static string TextContentSectionHeader {
        get {
            return ResourceManager.GetString("TextContentSectionHeader", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Book Title.
    /// </summary>
    public static string TitleProperty {
        get {
            return ResourceManager.GetString("TitleProperty", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Updating m4b metadata.
    /// </summary>
    public static string UpdatingM4bMetadataMessage {
        get {
            return ResourceManager.GetString("UpdatingM4bMetadataMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Please select voice.
    /// </summary>
    public static string VoicePlaceholder {
        get {
            return ResourceManager.GetString("VoicePlaceholder", resourceCulture);
        }
    }
}
