//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YewCone.AudiobookGenerator.Wpf {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YewCone.AudiobookGenerator.Wpf.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Image....
        /// </summary>
        public static string AddImageLable {
            get {
                return ResourceManager.GetString("AddImageLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need more voices?.
        /// </summary>
        public static string AddVoiceLable {
            get {
                return ResourceManager.GetString("AddVoiceLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://support.microsoft.com/en-us/topic/download-languages-and-voices-for-immersive-reader-read-mode-and-read-aloud-4c83a8d8-7486-42f7-8e46-2b0fdf753130.
        /// </summary>
        public static string AddVoiceLink {
            get {
                return ResourceManager.GetString("AddVoiceLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audiobook Generator.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        public static string BookLable {
            get {
                return ResourceManager.GetString("BookLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select ebook file.
        /// </summary>
        public static string BookPathPlaceholder {
            get {
                return ResourceManager.GetString("BookPathPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} chapters).
        /// </summary>
        public static string ChaptersLable {
            get {
                return ResourceManager.GetString("ChaptersLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover Image.
        /// </summary>
        public static string CoverImageLable {
            get {
                return ResourceManager.GetString("CoverImageLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string DetailsSectionHeader {
            get {
                return ResourceManager.GetString("DetailsSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Audiobook.
        /// </summary>
        public static string GenerateLable {
            get {
                return ResourceManager.GetString("GenerateLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} images).
        /// </summary>
        public static string ImagesLable {
            get {
                return ResourceManager.GetString("ImagesLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string ImagesSectionHeader {
            get {
                return ResourceManager.GetString("ImagesSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select ebook file.
        /// </summary>
        public static string NoBookPathPlaceholder {
            get {
                return ResourceManager.GetString("NoBookPathPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string PlayTooltip {
            get {
                return ResourceManager.GetString("PlayTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Image As....
        /// </summary>
        public static string SaveImageAsLable {
            get {
                return ResourceManager.GetString("SaveImageAsLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Book....
        /// </summary>
        public static string SelectBookLable {
            get {
                return ResourceManager.GetString("SelectBookLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string StopToolTip {
            get {
                return ResourceManager.GetString("StopToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Content.
        /// </summary>
        public static string TextContentSectionHeader {
            get {
                return ResourceManager.GetString("TextContentSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice.
        /// </summary>
        public static string VoiceLable {
            get {
                return ResourceManager.GetString("VoiceLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Name.
        /// </summary>
        public static string VoicePlaceholder {
            get {
                return ResourceManager.GetString("VoicePlaceholder", resourceCulture);
            }
        }
    }
}
