name: Publish executable

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        runtime: [win-x64, win-arm64]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Publish
      run: dotnet publish --runtime ${{ matrix.runtime }}

    - name: Publish Self Contained
      run: dotnet publish --runtime ${{ matrix.runtime }} --self-contained

    - name: Upload build artifacts
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: $env:Runtime
        path: artifact/**/YewCone.*.exe
